spring.application.name=ecommerce

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_java?useSSL=false&serverTimezone=Asia/Jakarta&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Konfigurasi Circuit Breaker untuk 'paymentGateway'
resilience4j.circuitbreaker.instances.paymentGateway.sliding-window-type=COUNT_BASED
# Menghitung statistik berdasarkan 10 request terakhir
resilience4j.circuitbreaker.instances.paymentGateway.sliding-window-size=10
# Jika 50% atau lebih dari 10 request terakhir itu eror/timeout, sirkuit langsung OPEN (Putus koneksi)
resilience4j.circuitbreaker.instances.paymentGateway.failure-rate-threshold=50
# Durasi sikit bertahan dalam kondisi OPEN sebelum mencoba masuk ke kondisi HALF-OPEN (mencoba nge-hit lagi)
resilience4j.circuitbreaker.instances.paymentGateway.wait-duration-in-open-state=10s
# Jika durasi eksekusi API pihak ketiga lebih dari 2.5 detik, hitung itu sebagai slow call / kegagalan terselubung
resilience4j.circuitbreaker.instances.paymentGateway.slow-call-duration-threshold=2500ms
resilience4j.circuitbreaker.instances.paymentGateway.slow-call-rate-threshold=70